graph LR
    analytics_service["analytics-service"]
    dashboard_service["dashboard-service"]
    email_service["email-service"]
    notification_service["notification-service"]
    order_service["order-service"]
    webapp_service["webapp-service"]
    audit_topic_exchange{{"audit.topic.exchange"}}
    email_service_direct_exchange_request["email-service.direct.exchange.request"]
    email_service_headers_exchange_response(("email-service.headers.exchange.response"))
    events_topic_exchange{{"events.topic.exchange"}}
    audit_topic_exchange -->|"order.#"| analytics_service
    email_service_direct_exchange_request -->|"email.send"| email_service
    email_service_headers_exchange_response -.->|"email.send"| webapp_service
    events_topic_exchange -->|"Order.#"| dashboard_service
    events_topic_exchange -->|"Order.Created"| notification_service
    order_service --> audit_topic_exchange
    order_service --> events_topic_exchange
    webapp_service --> email_service_direct_exchange_request
    style analytics_service,dashboard_service,email_service,notification_service,order_service,webapp_service fill:#f9f,stroke:#333
    style audit_topic_exchange,email_service_direct_exchange_request,email_service_headers_exchange_response,events_topic_exchange fill:#bbf,stroke:#333
